name: Calculator
options:
  bundleIdPrefix: com.mohammedu
targets:
  Calculator:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mohammedu.calculator
        PRODUCT_NAME: Calculator
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        ALWAYS_SEARCH_USER_PATHS: NO
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
